version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    restart: on-failure
    env_file:
      - .env
    command: ./apiserver

  db:
    image: postgres:alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data: